@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Apr 21 18:49:41 -0400 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 704f60f7360645ebba906a2fa0b59cea --incr --debug typical --relax --mt 2 -L axis_infrastructure_v1_1_0 -L axis_register_slice_v1_1_19 -L axis_dwidth_converter_v1_1_18 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Acquisition_top_behav xil_defaultlib.Acquisition_top xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 704f60f7360645ebba906a2fa0b59cea --incr --debug typical --relax --mt 2 -L axis_infrastructure_v1_1_0 -L axis_register_slice_v1_1_19 -L axis_dwidth_converter_v1_1_18 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Acquisition_top_behav xil_defaultlib.Acquisition_top xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
