@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 10 16:00:14 -0400 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim start_trig_logic_behav -key {Behavioral:sim_1:Functional:start_trig_logic} -tclbatch start_trig_logic.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_f60c.protoinst" -log simulate.log"
call xsim  start_trig_logic_behav -key {Behavioral:sim_1:Functional:start_trig_logic} -tclbatch start_trig_logic.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_f60c.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
