# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Red_Pitaya/Acq_Card/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_1/design_1_dds_compiler_0_1.xci
# IP: The module: 'design_1_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Red_Pitaya/Acq_Card/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_1/design_1_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Red_Pitaya/Acq_Card/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_1/design_1_dds_compiler_0_1.xci
# IP: The module: 'design_1_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Red_Pitaya/Acq_Card/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_1/design_1_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
